notifications:
  recipients:
    - groonga-commit@lists.sourceforge.jp
language: ruby
rvm:
  - 1.9.3
before_install:
  - curl --silent --location https://github.com/groonga/groonga/raw/master/data/travis/setup.sh | sh
